name: CI
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Adicionando mensagenss de log
        run: |
          echo "::debug:: Mensagem de log debug"
          echo "::warning:: Mensagem de warning"
          echo "::notice:: Mensagem de log notice"
          echo "::error:: Mensagem de error executado por ${{ github.actor }}"

    